server:
  port: 8000



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bishe?useSSL=false
    username: root
    password: "0528"
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.liuhao.bishe.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  activemq:
    broker-url: tcp://192.168.43.66:61616
    user: admin
    password: admin
  jms:
    # 目的地是queue还是topic， false（默认） = queue    true =  topic
    pub-sub-domain: true

  #  自定义主题名称
mytopic: SW_LED
hum: Huminity


mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

